### ISSUE TITLE
Unintuitive ordering of signed integers in keys

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/storey#63]
Right now, `Key` is implemented for signed integer types using a straight forward BE encoding. However, this leads to the following iteration order:

- 0
- 1 … iXX::MAX
- iXX::MIN … -1

So the negative numbers sorted after the positive ones.

In cw-storage-plus this is avaided by a custom binary encoding for signed integers ([some smart trick I never looked into in detail](https://github.com/CosmWasm/cw-storage-plus/blob/v2.0.0/src/int_key.rs#L3-L52)).

I think we should address this somehow to avoid unexpected iteration order. Either by implementing what we do in cw-storage-plus, remove support for signed integers or something better.

**Comment by uint** [comment]
Yeah, I missed that. Sounds both high prio and easy to do.
